[package]
name = "exprs"
version = "0.1.0"
authors = ["Assaf Sapir <assapir@github.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/assapir/keyvaluers/tree/main/exprs"

[dependencies]
json = "0.12.4"
num_cpus = "1.13.0"
